export enum Tag {
  LEAVE_POLICIES = 'LeavePolicies',
  MY_LEAVE_POLICIES = 'MyLeavePolicies',
  CLASSES = 'Classes',
  CLASS_TEACHERS = 'ClassTeachers',
  STUDENTS = 'Students',
  NOTICES = 'Notices',
  NOTICE_RECIPIENT_LIST = 'NoticeRecipientList',
  NOTICE_RECIPIENTS = 'NoticeRecipients',
  STAFFS = 'Staffs',
  DASHBOARD = 'Dashboard',
  LEAVE_HISTORY = 'LeaveHistory',
  PENDING_LEAVES = 'PendingLeaves',
  LEAVE_ELIGIBLE_USERS = 'LeaveEligibleUsers',
  LEAVE_POLICY_USERS = 'LeavePolicyUsers',
  ROLES = 'Roles',
  PERMISSIONS = 'Permissions',
  MY_PERMISSIONS = 'MyPermissions',
  ROLE_USERS = 'RoleUsers',
  ROLE_PERMISSIONS = 'RolePermissions',
  SECTIONS = 'Sections',
  DEPARTMENTS = 'Departments',
  PENDING_NOTICES = 'PendingNotices'
}
